import { FeatureType } from "./Components";

export const SlackLink =
  "https://join.slack.com/t/graphqleditor/shared_invite/enQtNDkwOTgyOTM5OTc1LWI4YjU3N2U5NGVkNzQ2NzY5MGUxMTJiNjFlZDM1Zjc2OWRmNTI0NDM3OWUxYTk4Yjk3MzZlY2QwOWUzZmM2NDI";

// ************************ Home ************************

export const whyYouShouldData = [
  {
    imgSrc: require("../assets/images/optimised.svg"),
    imgAlt: "zdjecie",
    title: "GRAPHQL SUPER EASY",
    description: `There is no graphql knowledge required to start using this editor. Just click and experiment to learn this technology of future.`
  },
  {
    imgSrc: require("../assets/images/powerfull.svg"),
    imgAlt: "zdjecie",
    title: "THINK VISUALLY",
    description: `All backend systems should be drawn first. It is much easier to get the desired solution if you see your system and its structure.`
  },
  {
    imgSrc: require("../assets/images/website.svg"),
    imgAlt: "zdjecie",
    title: "NO CODE SOLUTION",
    description: `You can create graphql server without modifying generated code. Code generated by editor is ready to use in production.`
  }
];

export const trustedList = [
  {
    address: "https://divante.co",
    imgSrc: require("../assets/images/divante.svg"),
    altImg: "divante"
  },
  {
    address: "https://facebook.com",
    imgSrc: require("../assets/images/Facebook.png"),
    altImg: "facebook"
  },
  {
    address: "https://netguru.co",
    imgSrc: require("../assets/images/netguru.svg"),
    altImg: "netguru"
  },
  {
    address: "https://instagram.com",
    imgSrc: require("../assets/images/instagram.png"),
    altImg: "instagram"
  },
  {
    address: "https://twitter.com",
    imgSrc: require("../assets/images/twitter.png"),
    altImg: "twitter"
  },
  {
    address: "https://asana.com/",
    imgSrc: require("../assets/images/asana.png"),
    altImg: "asana"
  },
  {
    address: "https://www.producthunt.com/",
    imgSrc: require("../assets/images/product_hunt.png"),
    altImg: "product hunt"
  },
  {
    address: "https://www.pinterest.com/",
    imgSrc: require("../assets/images/pinterest.png"),
    altImg: "pinterest"
  },
  {
    address: "https://www.github.com/",
    imgSrc: require("../assets/images/github.png"),
    altImg: "github"
  },
  {
    address: "https://www.paypal.com/",
    imgSrc: require("../assets/images/paypal.png"),
    altImg: "paypal"
  }
];

// ************************ PRICING LIST ************************

export const roadmapData: FeatureType[] = [
  {
    imgSrc: require("../assets/images/vps.svg"),
    imgAlt: "hosting",
    title: "ACCOUNTS & PROJECTS",
    description: "Create projects and save them on your account",
    date: "DONE"
  },
  {
    imgSrc: require("../assets/images/server.svg"),
    imgAlt: "server",
    title: "GENERATE QUERIES FOR FRONTEND",
    description:
      "Generate frontend typesafe libs for javascript/typescript. So you can have autocomplete for avaialble queries to speed up development",
    date: "DONE"
  },
  {
    imgSrc: require("../assets/images/powerfull.svg"),
    imgAlt: "hosting",
    title: "READY TO USE FAKE BACKEND",
    description:
      " If your backend is complicated and you need some backend dev to write resolvers. Don’t wait! Start your job without it.",
    date: "DONE"
  },
  {
    imgSrc: require("../assets/images/hosting2.svg"),
    imgAlt: "hosting",
    title: "COLLABORATION FEATURE",
    description: "Collaborate on projects in graphql editor.",
    date: "1 II 2019"
  },
  {
    imgSrc: require("../assets/images/hosting.svg"),
    imgAlt: "hosting",
    title: "GRAPHQL TO BACKEND",
    description:
      "Deploy mongo database with automagically generated resolvers in cloud for your GraphQL schema. So you don’t have to code backend.",
    q: 1,
    year: 2019
  },
  {
    imgSrc: require("../assets/images/website.svg"),
    imgAlt: "vps",
    title: "BACKEND FOR FRONTEND",
    description:
      "GraphQL schema is a mirror of your backend system. Keep it in cloud and collaborate on it. Together you can do more.",
    q: 1,
    year: 2019
  },
  {
    imgSrc: require("../assets/images/address-light.svg"),
    imgAlt: "vps",
    title: "INTELLIGENT QUERY RESOLVERS",
    description:
      "Resolvers created only from diagram recognising popular backend functions ( filter, order etc.) ",
    q: 2,
    year: 2019
  },
  {
    imgSrc: require("../assets/images/address-light.svg"),
    imgAlt: "vps",
    title: "INTEGRATIONS",
    description:
      "Integrations with popular graphql stacks like Hasura or Apollo ",
    q: 3,
    year: 2019
  }
];

// ************************ Recommendations Slider ************************

export const recommendationsData = [
  {
    imgSrc: require("../assets/images/brand.png"),
    imgAlt: "logo-tesla",
    title: "Totaly Optimised 3",
    description: `It is a long established fact that a reader will be
    distracted by the readable content of a page when looking at
    its layout. The point of using Lorem Ipsum is that it has a
    more-or-less normal distribution of letters.`,
    address: "https://www.mcdonalds.com",
    person: "Lorem Ipsum 1",
    personImg: "",
    position: "Master of Philosophy at McDonald's"
  },
  {
    imgSrc: require("../assets/images/brand.png"),
    imgAlt: "logo-tesla",
    title: "Totaly Optimised 3",
    description: `It is a long established fact that a reader will be
    distracted by the readable content of a page when looking at
    its layout. The point of using Lorem Ipsum is that it has a
    more-or-less normal distribution of letters.`,
    address: "https://www.mcdonalds.com",
    person: "Lorem Ipsum 2",
    personImg: "../assets/images/user.png",
    position: "Master of Philosophy at McDonald's"
  }
];

// ************************ Footer ************************

export const footerData = [
  {
    title: "Menu",
    links: [
      "Services",
      "Roadmap",
      "Slack Community",
      "GraphQL Blog",
      "GraphQL Editor",
      "Docs"
    ],
    linksTo: [
      "/services",
      "#roadmap",
      SlackLink,
      "https://blog.graphqleditor.com",
      "https://app.graphqleditor.com",
      "https://docs.graphqleditor.com"
    ]
  },
  {
    title: "Examples",
    links: [
      "GraphQL Example #1: Fake Twitter",
      "GraphQL Example #2: Library of books",
      "GraphQL Example #3: eCommerce"
    ],
    linksTo: [
      "https://app.graphqleditor.com/showcase/fake-twitter",
      "https://app.graphqleditor.com/showcase/library",
      "https://app.graphqleditor.com/showcase/shop"
    ]
  }
];

// ************************ ABOUT ************************

export const ourTeam = [
  {
    imgSrc: require("../assets/images/team-img.png"),
    name: "John Ipsum",
    position: "developer"
  },
  {
    imgSrc: require("../assets/images/team-img.png"),
    name: "John Ipsum",
    position: "developer"
  },
  {
    imgSrc: require("../assets/images/team-img.png"),
    name: "John Ipsum",
    position: "developer"
  },
  {
    imgSrc: require("../assets/images/team-img.png"),
    name: "John Ipsum",
    position: "developer"
  },
  {
    imgSrc: require("../assets/images/team-img.png"),
    name: "John Ipsum",
    position: "developer"
  },
  {
    imgSrc: require("../assets/images/team-img.png"),
    name: "John Ipsum",
    position: "developer"
  },
  {
    imgSrc: require("../assets/images/team-img.png"),
    name: "John Ipsum",
    position: "developer"
  },
  {
    imgSrc: require("../assets/images/team-img.png"),
    name: "John Ipsum",
    position: "developer"
  }
];

// ************************ SERVICE ************************

export const monthPlans = [
  {
    imgSrc: require("../assets/images/basic-plan.svg"),
    title: "Basic",
    list: [
      "for individuals",
      "Unlimited File Storage",
      "3 Projects",
      "2 Members",
      "30d Version history"
    ],
    price: 0
  },
  {
    imgSrc: require("../assets/images/star-plan.png"),
    title: "Professional",
    list: [
      "Everything in Basic plus",
      "Unlimited free viewers",
      "Unlimited projects",
      "Unlimited files",
      " Unlimited version history",
      "Team library",
      "Private projects"
    ],
    price: 12
  },
  {
    imgSrc: require("../assets/images/hosting.svg"),
    title: "Organization",
    list: [
      "Everything in Professional plus",
      "Unlimited teams",
      "Organization-wide design systems",
      "Advanced access controls & Privacy settings",
      "Enforced SSO",
      "Enforced 2FA",
      "SAML-based SSO",
      "Audit Reports"
    ],
    price: "45"
  }
];

// ************************ USER INTERFACE ************************

export const userNav = [
  {
    title: "MY PLANS",
    icon: "fas fa-server",
    componentTitle: "SelectedPlan",
    logout: false
  },
  {
    title: "PERSONAL INFORMATION",
    icon: "far fa-user",
    componentTitle: "PersonalInfo",
    logout: false
  },
  {
    title: "PAYMENTS",
    icon: "fas fa-credit-card",
    componentTitle: "PaymentsInfo",
    logout: false
  },
  {
    title: "LOG OUT",
    icon: "fas fa-sign-out-alt",
    logout: true
  }
];

export const userAddress = {
  Name: "Holly K Douglas",
  Address: "4124 Wines Lane",
  City: "LITTLE ROCK",
  State: "Arkansas",
  ZIP: "72214",
  Country: "USA"
};

export type ConsultingTile = {
  name: string;
  description: string;
  image: string;
  points: string[];
};
export const consultingTiles: ConsultingTile[] = [
  {
    name: "BaaS - Backend as a Service",
    image: require("../assets/images/hosting2.svg"),
    description:
      "We create & deploy backend based on GraphQL Schema as a source of truth. You get frontend graphql interface and complete support package and more:",
    points: [
      "A customized GraphQL Visual Editor for your organization, and a handbook for onboarding new teams.",
      "Regular, scheduled reviews of GraphQL performance, security, tailored to your team and requirements.",
      "A Technical Account Manager understanding your business needs and makes sure you’re getting what you need.",
      "A GraphQL Senior Expert who works with your team through every phase of development, on-site or on-line."
    ]
  }
];
