export * from './Header';
export * from "./Home";
export * from "./Footer";
export * from "./SearchDomain";
export * from './AboutUs';
export * from './NotFound';
export * from './LoginSignUp';
export * from './Contact';
export * from './Service';